package com.tezov.bluetooth

import java.util.concurrent.TimeUnit

object Constantes {
    //LOCATION CONFIG

    //REQUEST PERMISSION CODE
    val PERMISSION_ACCESS_FINE_LOCATION_REQUEST_CODE = 1
    val PERMISSION_ACCESS_COARSE_LOCATION_REQUEST_CODE = 2

    val PERMISSION_BLUETOOTH_ADMIN_REQUEST_CODE = 3
    val PERMISSION_BLUETOOTH_CONNECT_REQUEST_CODE = 4
    val PERMISSION_BLUETOOTH_SCAN_REQUEST_CODE = 5

    //START FOR RESULT CODE
    val ENABLE_BLUETOOTH_REQUEST_CODE = 41




}